apiVersion: apps/v1
kind: Deployment
metadata:
  name: p2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: p2
  template:
    metadata:
      labels:
        app: p2
    spec:
      containers:
      - image: dorowu/ubuntu-desktop-lxde-vnc:focal-lxqt
        name: p2
        ports:
        - containerPort: 80
